variables:
  DOCKER_REGISTRY: 038062473746.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: team-gitlab-hackathon/frontend
  DOCKER_HOST: tcp://docker:2375

deploy:
  stage: deploy
  image: bearengineer/awscli-kubectl
  script:
    - aws eks update-kubeconfig --region us-east-1 --name basic-cluster
    - sed -i "s/<VERSION>/${DOCKER_IMAGE}/g" deployment.yml
    - kubectl apply -f deployment.yml -n=gitlab-ci
    - kubectl apply -f service.yml -n=gitlab-ci
